<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TipologiasDocumentalesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insertar tipologías documentales solo si no existen
        $tipologias = [
            [
                'id' => 1,
                'codigo' => 'TIP-001',
                'nombre' => 'Acta de Reunión',
                'descripcion' => 'Documentos que registran formalmente las reuniones y decisiones tomadas',
                'categoria' => 'administrativo',
                'grupo_tipologico' => 'actas',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['fecha_reunion', 'participantes', 'temas_tratados']),
                'metadatos_opcionales' => json_encode(['observaciones', 'anexos']),
                'reglas_validacion' => json_encode(['min_participantes' => 3]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Capturar inmediatamente después de la reunión',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'codigo' => 'TIP-002',
                'nombre' => 'Correspondencia',
                'descripcion' => 'Comunicaciones oficiales internas y externas',
                'categoria' => 'comunicaciones',
                'grupo_tipologico' => 'correspondencia',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx', 'jpg', 'png']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => false,
                'metadatos_obligatorios' => json_encode(['remitente', 'destinatario', 'asunto']),
                'metadatos_opcionales' => json_encode(['urgencia', 'clasificacion']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'codigo' => 'TIP-003',
                'nombre' => 'Informe Técnico',
                'descripcion' => 'Reportes técnicos especializados y análisis',
                'categoria' => 'tecnico',
                'grupo_tipologico' => 'informes',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx', 'xls', 'xlsx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['autor_tecnico', 'area_especialidad', 'fecha_elaboracion']),
                'metadatos_opcionales' => json_encode(['revisado_por', 'anexos_tecnicos']),
                'reglas_validacion' => json_encode(['min_paginas' => 5]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Validar firma del responsable técnico',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'codigo' => 'TIP-004',
                'nombre' => 'Contrato',
                'descripcion' => 'Documentos contractuales y convenios',
                'categoria' => 'legal',
                'grupo_tipologico' => 'contratos',
                'formatos_aceptados' => json_encode(['pdf']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['partes_contrato', 'objeto_contrato', 'vigencia', 'valor']),
                'metadatos_opcionales' => json_encode(['clausulas_especiales', 'garantias']),
                'reglas_validacion' => json_encode(['requiere_valor' => true, 'min_vigencia_dias' => 30]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Verificar todas las firmas antes de capturar',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'codigo' => 'TIP-005',
                'nombre' => 'Documento General',
                'descripcion' => 'Documentos diversos sin clasificación específica',
                'categoria' => 'general',
                'grupo_tipologico' => 'varios',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx', 'jpg', 'png', 'xls', 'xlsx', 'mp4', 'mp3']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => false,
                'metadatos_obligatorios' => json_encode(['titulo_documento', 'descripcion']),
                'metadatos_opcionales' => json_encode(['palabras_clave', 'observaciones']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'codigo' => 'TIP-006',
                'nombre' => 'Lista de Asistencia',
                'descripcion' => 'Registro de asistencia a reuniones, capacitaciones o eventos',
                'categoria' => 'administrativo',
                'grupo_tipologico' => 'registros',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'png']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => false,
                'metadatos_obligatorios' => json_encode(['fecha_evento', 'nombre_evento', 'responsable']),
                'metadatos_opcionales' => json_encode(['lugar', 'hora_inicio', 'hora_fin', 'total_asistentes']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Escanear con todas las firmas visibles',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'codigo' => 'TIP-007',
                'nombre' => 'Resolución',
                'descripcion' => 'Actos administrativos de carácter particular o general',
                'categoria' => 'legal',
                'grupo_tipologico' => 'actos_administrativos',
                'formatos_aceptados' => json_encode(['pdf']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['numero_resolucion', 'fecha_expedicion', 'objeto']),
                'metadatos_opcionales' => json_encode(['considerandos', 'resuelve', 'notificaciones']),
                'reglas_validacion' => json_encode(['requiere_numero' => true]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Verificar número consecutivo y firmas',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'codigo' => 'TIP-008',
                'nombre' => 'Circular',
                'descripcion' => 'Comunicaciones de carácter general dirigidas a múltiples destinatarios',
                'categoria' => 'comunicaciones',
                'grupo_tipologico' => 'correspondencia',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['numero_circular', 'fecha', 'dirigido_a', 'asunto']),
                'metadatos_opcionales' => json_encode(['vigencia', 'anexos']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'codigo' => 'TIP-009',
                'nombre' => 'Memorando',
                'descripcion' => 'Comunicaciones internas entre dependencias o funcionarios',
                'categoria' => 'comunicaciones',
                'grupo_tipologico' => 'correspondencia',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => false,
                'metadatos_obligatorios' => json_encode(['de', 'para', 'asunto', 'fecha']),
                'metadatos_opcionales' => json_encode(['copia', 'anexos', 'urgencia']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'codigo' => 'TIP-010',
                'nombre' => 'Certificado',
                'descripcion' => 'Documentos que dan fe de hechos, situaciones o calidades',
                'categoria' => 'legal',
                'grupo_tipologico' => 'certificaciones',
                'formatos_aceptados' => json_encode(['pdf']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['numero_certificado', 'beneficiario', 'concepto', 'fecha_expedicion']),
                'metadatos_opcionales' => json_encode(['vigencia', 'observaciones']),
                'reglas_validacion' => json_encode(['requiere_numero' => true]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Verificar firma y sello institucional',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'codigo' => 'TIP-011',
                'nombre' => 'Constancia',
                'descripcion' => 'Documentos que acreditan hechos o situaciones específicas',
                'categoria' => 'administrativo',
                'grupo_tipologico' => 'certificaciones',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['beneficiario', 'concepto', 'fecha_expedicion']),
                'metadatos_opcionales' => json_encode(['periodo', 'cargo', 'observaciones']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'codigo' => 'TIP-012',
                'nombre' => 'Factura',
                'descripcion' => 'Documentos comerciales de compra y venta',
                'categoria' => 'contable',
                'grupo_tipologico' => 'financiero',
                'formatos_aceptados' => json_encode(['pdf', 'xml']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => false,
                'metadatos_obligatorios' => json_encode(['numero_factura', 'proveedor', 'valor_total', 'fecha']),
                'metadatos_opcionales' => json_encode(['nit_proveedor', 'detalle_productos', 'impuestos']),
                'reglas_validacion' => json_encode(['requiere_valor' => true]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Verificar resolución DIAN',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'codigo' => 'TIP-013',
                'nombre' => 'Orden de Compra',
                'descripcion' => 'Documentos de solicitud formal de bienes o servicios',
                'categoria' => 'contable',
                'grupo_tipologico' => 'financiero',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['numero_orden', 'proveedor', 'valor', 'fecha']),
                'metadatos_opcionales' => json_encode(['especificaciones', 'plazo_entrega', 'condiciones']),
                'reglas_validacion' => json_encode(['requiere_valor' => true]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'codigo' => 'TIP-014',
                'nombre' => 'Acta de Entrega',
                'descripcion' => 'Documentos que formalizan la entrega de bienes, cargos o proyectos',
                'categoria' => 'administrativo',
                'grupo_tipologico' => 'actas',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['fecha_entrega', 'entrega', 'recibe', 'objeto_entrega']),
                'metadatos_opcionales' => json_encode(['inventario', 'observaciones', 'estado']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Verificar firmas de quien entrega y quien recibe',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'codigo' => 'TIP-015',
                'nombre' => 'Plan de Trabajo',
                'descripcion' => 'Documentos de planificación de actividades y proyectos',
                'categoria' => 'administrativo',
                'grupo_tipologico' => 'planes',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => false,
                'metadatos_obligatorios' => json_encode(['nombre_plan', 'responsable', 'periodo', 'objetivos']),
                'metadatos_opcionales' => json_encode(['recursos', 'cronograma', 'indicadores']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'codigo' => 'TIP-016',
                'nombre' => 'Manual o Procedimiento',
                'descripcion' => 'Documentos normativos que establecen procedimientos o instrucciones',
                'categoria' => 'normativo',
                'grupo_tipologico' => 'manuales',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['codigo_documento', 'nombre', 'version', 'fecha_aprobacion']),
                'metadatos_opcionales' => json_encode(['proceso', 'elaboro', 'reviso', 'aprobo']),
                'reglas_validacion' => json_encode(['requiere_version' => true]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Verificar versión vigente',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'codigo' => 'TIP-017',
                'nombre' => 'Formato o Plantilla',
                'descripcion' => 'Formatos estandarizados para registro de información',
                'categoria' => 'normativo',
                'grupo_tipologico' => 'formatos',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx', 'xls', 'xlsx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => false,
                'metadatos_obligatorios' => json_encode(['codigo_formato', 'nombre', 'version']),
                'metadatos_opcionales' => json_encode(['proceso', 'instrucciones']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'codigo' => 'TIP-018',
                'nombre' => 'Informe de Gestión',
                'descripcion' => 'Reportes periódicos de avances y resultados de gestión',
                'categoria' => 'administrativo',
                'grupo_tipologico' => 'informes',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx', 'ppt', 'pptx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['periodo', 'area', 'responsable', 'fecha']),
                'metadatos_opcionales' => json_encode(['logros', 'dificultades', 'indicadores', 'anexos']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'codigo' => 'TIP-019',
                'nombre' => 'Cotización',
                'descripcion' => 'Ofertas comerciales de proveedores',
                'categoria' => 'contable',
                'grupo_tipologico' => 'financiero',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx', 'xls', 'xlsx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => false,
                'metadatos_obligatorios' => json_encode(['proveedor', 'fecha', 'valor_total']),
                'metadatos_opcionales' => json_encode(['vigencia', 'condiciones', 'detalle_productos']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'codigo' => 'TIP-020',
                'nombre' => 'Historia Clínica',
                'descripcion' => 'Registro médico de pacientes (sector salud)',
                'categoria' => 'clinico',
                'grupo_tipologico' => 'historias_clinicas',
                'formatos_aceptados' => json_encode(['pdf']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['numero_historia', 'paciente', 'identificacion', 'fecha']),
                'metadatos_opcionales' => json_encode(['diagnostico', 'tratamiento', 'medico_tratante']),
                'reglas_validacion' => json_encode(['confidencial' => true]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Documento confidencial - Ley 1581',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'codigo' => 'TIP-021',
                'nombre' => 'Hoja de Vida',
                'descripcion' => 'Formato de información personal y laboral',
                'categoria' => 'recursos_humanos',
                'grupo_tipologico' => 'personal',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => false,
                'metadatos_obligatorios' => json_encode(['nombre_completo', 'identificacion', 'cargo_aspirado']),
                'metadatos_opcionales' => json_encode(['experiencia', 'formacion', 'referencias']),
                'reglas_validacion' => json_encode(['confidencial' => true]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Documento confidencial',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'codigo' => 'TIP-022',
                'nombre' => 'Nómina',
                'descripcion' => 'Documentos de liquidación de salarios',
                'categoria' => 'recursos_humanos',
                'grupo_tipologico' => 'nomina',
                'formatos_aceptados' => json_encode(['pdf', 'xls', 'xlsx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['periodo', 'total_nomina', 'numero_empleados']),
                'metadatos_opcionales' => json_encode(['deducciones', 'aportes', 'observaciones']),
                'reglas_validacion' => json_encode(['confidencial' => true, 'requiere_valor' => true]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Documento confidencial',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'codigo' => 'TIP-023',
                'nombre' => 'Acta de Comité',
                'descripcion' => 'Actas de comités institucionales específicos',
                'categoria' => 'administrativo',
                'grupo_tipologico' => 'actas',
                'formatos_aceptados' => json_encode(['pdf', 'doc', 'docx']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['numero_acta', 'comite', 'fecha', 'asistentes']),
                'metadatos_opcionales' => json_encode(['orden_del_dia', 'compromisos', 'proxima_reunion']),
                'reglas_validacion' => json_encode(['min_participantes' => 3]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Verificar firmas de presidente y secretario',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'codigo' => 'TIP-024',
                'nombre' => 'Poder o Autorización',
                'descripcion' => 'Documentos de delegación de facultades',
                'categoria' => 'legal',
                'grupo_tipologico' => 'poderes',
                'formatos_aceptados' => json_encode(['pdf']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => true,
                'metadatos_obligatorios' => json_encode(['otorgante', 'apoderado', 'facultades', 'vigencia']),
                'metadatos_opcionales' => json_encode(['limitaciones', 'notaria']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => 'Verificar autenticación si aplica',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'codigo' => 'TIP-025',
                'nombre' => 'Fotografía o Evidencia Visual',
                'descripcion' => 'Registros fotográficos de eventos o evidencias',
                'categoria' => 'multimedia',
                'grupo_tipologico' => 'audiovisual',
                'formatos_aceptados' => json_encode(['jpg', 'jpeg', 'png', 'gif', 'tiff']),
                'version' => 1,
                'activa' => true,
                'requiere_firma_digital' => false,
                'metadatos_obligatorios' => json_encode(['fecha_captura', 'descripcion', 'ubicacion']),
                'metadatos_opcionales' => json_encode(['evento', 'fotografo', 'equipo']),
                'reglas_validacion' => json_encode([]),
                'plantilla_metadatos' => json_encode([]),
                'notas_captura' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        
        foreach ($tipologias as $tipologia) {
            $exists = DB::table('tipologias_documentales')->where('id', $tipologia['id'])->exists();
            if (!$exists) {
                DB::table('tipologias_documentales')->insert($tipologia);
            }
        }
        
        echo "✅ Tipologías documentales creadas exitosamente.\n";
    }
}
